n1 = input('Digite algo: ')
print(n1.isspace(), '= Tem espaços?')
print(n1.isnumeric(), '= Tem números?')
print(n1.isalpha(), '= Tem letras?')
print(n1.isalnum(), '= Tem letras ou números?')
print(n1.isupper(), '= É caixa alto?')
print(n1.islower(), '= É caixa baixo?')
print(n1.istitle(), '= Está capitalizada?')